# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
   echo "#! /bin/bash" > $(Pipeline.Workspace)/hiptest-publisher
   echo "docker run --rm --volume=\"$(pwd):/app\" hiptest/hiptest-publisher  \"\$@\"" >> $(Pipeline.Workspace)/hiptest-publisher
   sudo chmod +x $(Pipeline.Workspace)/hiptest-publisher
  displayName: 'Installing hiptest-publisher docker script as an executable file'
- script: $(Pipeline.Workspace)/hiptest-publisher -c cucumber-java.conf --token=$(PROJECT_TOKEN) --test-run-id=$(TEST_RUN_ID) --without=actionwords
  displayName: 'Updating feature files and fetch UIDs of tests'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
- script: mvn test 
  displayName: 'Run tests'
- script: $(Pipeline.Workspace)/hiptest-publisher -c cucumber-java.conf --token=$(PROJECT_TOKEN) -p="target/cuke-results.json" --test-run-id=$(TEST_RUN_ID)
  displayName: 'Push JSON report to CucumberStudio test run'