# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn --file ${GITHUB_WORKSPACE}/pom.xml test
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install @cucumber/json-to-messages
    - name: convert report file to the supported CucumberStudio format
      run: cat ${GITHUB_WORKSPACE}/target/cuke-results.json | ./node_modules/.bin/json-to-messages > ${GITHUB_WORKSPACE}/target/cuke-results.ndjson
    - name: check if ndjson has been properly generated
    - name: Push report file to CucumberStudio living documentation
      run: curl -X POST https://studio.cucumber.io/cucumber_project/results -F messages=@${GITHUB_WORKSPACE}/target/cuke-results.ndjson -H "project-access-token: 274619479310218793134342586214047524212722623749771759839" -H "provider: gitlab" -H "repo: houdabou/hps-cucumber-java" -H "branch: master" -H "revision: ${GITHUB_SHA}"
